# Generated by Django 5.1.1 on 2024-12-29 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0007_item_purchaserequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='class_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_items', to='class.class'),
        ),
    ]
